# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'undelivery_rn_tmp' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )

    installer.pods_project.targets.each do |target|
      next unless target.name == 'react-native-safe-area-context'

      target.build_configurations.each do |build_config|
        header_search_paths = build_config.build_settings['HEADER_SEARCH_PATHS'] || '$(inherited)'
        header_search_paths = [header_search_paths] unless header_search_paths.is_a?(Array)

        header_search_paths << '$(PODS_ROOT)/../build/generated/ios/ReactCodegen'
        build_config.build_settings['HEADER_SEARCH_PATHS'] = header_search_paths.uniq
      end
    end
  end
end
